[tool.poetry]
name = "project-with-htmx"
version = "0.1.0"
description = ""
authors = ["CarAndAsh <zeixes@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
